name: End To End Tests

on:
  pull_request:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install winget (Windows)
        if: runner.os == 'Windows'
        uses: Cyberboss/install-winget@v1

      - name: Install Neovim (Windows) and add to PATH
        if: runner.os == 'Windows'
        run: |
          winget install Neovim.Neovim --silent --accept-package-agreements --accept-source-agreements
          echo "$Env:ProgramFiles\Neovim\bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Install Neovim (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install neovim

      - name: Install Neovim (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y neovim

      - name: Run Neovim tests
        run: |
          nvim --headless -u NONE -c "lua dofile('runtests.lua')"
